# few_shot_examples.py
# This file stores high-quality writing samples for different sections of a paper
# to be used as few-shot examples for the language model.

INTRODUCTION_FEW_SHOT_EXAMPLE = """
### 1. Introduction
Ultrasound is widely established clinically, both for diagnostic and therapeutic purposes (e.g., lithotripsy, tumor ablation). Therapeutic effects can be induced by thermal or non-thermal mechanisms. Thermal ablation employes long duty cycles and a low mechanical index to emit high intensities, which locally heat the tissue to 50–100 ◦C, resulting in coagulation and cell necrosis [1]. Hyperthermia is defined as the heating of tissue to a temperature of 40–43 ◦C at low ultrasound intensities for a duration of up to one hour, resulting in a multitude of  effects, including increased tumor perfusion and altered DNA repair pathways [2]. Hyperthermia can act as a radio- or chemosensitizer [3] by enhancing drug delivery into the tumor and improving the response of tumor cells towards therapy. The transferred ultrasound energy can also be used during sonodynamic therapy to activate sono-sensitizers (e. g., protophorphyrins, chlorophyll derivatives, hematoporphyrin derivatives) without significant tissue heating, resulting in local tumor cell death by the generation of reactive oxygen species (ROS). The accumulation of sono-sensitizers in tumors can be enhanced by incorporating them into drug-delivery systems, such as nanoparticles. These systems can also be used in combination with other therapies, including chemotherapeutics and immunotherapies, by enabling their local release and enhancing their efficacy [4].

In contrast to thermal therapy approaches, mechanical ablation induces cavitation or boiling bubbles in the tissue by applying short ultrasound pulses at high pressure, resulting in tissue disruption without substantial heating [5]. Non-thermal effects, such as acoustic streaming, acoustic radiation force, or stable cavitation of gas bubbles in the tissue, can even occur during diagnostic ultrasound. However, no biological effects could be detected in vivo so far [6]. Sono-enhancers, e.g., gas-filled microbubbles, which are also widely used as contrast agents in diagnostic ultrasound, can enhance non-thermal effects. Applying lowpressure ultrasound pulses generates stable microbubble oscillation, leading to moderate shear stress on endothelial cells via acoustic microstreaming [7]. Increasing the pressure disrupts microbubbles, inducing inertial cavitation and generating reactive oxygen species or microjets that permanently damage nearby cells [8]. Furthermore, stable oscillation and disruption of microbubbles are the underlying mechanisms to open up biological barriers for drug delivery during sonopermeation or sonoporation [7,8]. In this regard, the tumor response depends not only on the ultrasound settings but also on the tumor stroma. Mature and well-stabilized vessels might respond less to destructive ultrasound, whereas very immature vessels might break down immediately [9]. Destructive ultrasound schemes including microbubble disruption are also applied when performing diagnostic measurements of tissue perfusion [10] or applying molecular ultrasound [11]. In general, cell damage can occur depending on the microbubble dose, ultrasound intensity, and sonication time [12–14]. Subtle changes may arise early but remain undetected. In particular, ultrasound might trigger immunological reactions.

Both thermal and non-thermal ultrasound therapy approaches have the potential to damage tumor cells, which subsequently release dangerassociated molecular patterns and activate innate immune cells [15], leading to T cell differentiation and activation [16]. However, hightemperature tumor ablation can attenuate anti-tumor immune responses by denaturing proteins, rendering them unrecognizable to immune cells [1]. Furthermore, depending on the ultrasound settings (e.g. mechanical ablation, non-thermal ultrasound with destruction of microbubbles), cavitation can induce tumor vessel collapse, preventing immune cell extravasation and inhibiting immune responses, or increase tumor vascularization and vascular permeability, leading to opposite effects [17]. 

Predicting the impact of ultrasound on immune responses is challenging, especially in preclinical research, due to substantial variations in experimental design and inadequate study design reporting [18]. Therefore, we conducted a systematic review and meta-analysis to provide more robust, evidence-based conclusions addressing the research question: Does ultrasound alter immune reactions of peripheral solid tumors in humans and animals compared to control conditions without ultrasound? Unlike conventional narrative reviews, which provide a descriptive overview of a subset of the literature, systematic reviews adhere to rigorous and transparent protocols. A comprehensive and systematic literature search ensures that all available literature is considered, data are extracted from the publications meeting specific criteria, and a systematic synthesis of evidence is provided, for example through the performance of a meta-analysis. Overall, the process generates more robust and evidence-based conclusions, which can be used to identify knowledge gaps, prevent unnecessary duplication of experiments, or refine the design of future experiments [19,20]. After registering and publishing the corresponding protocol [20], we now present the results of the systematic review and six meta-analyses regarding tumor-infiltrating T cells and inflammatory cytokines in the blood. Furthermore, we show which specific experimental characteristics influence study results. These results could help refining ultrasound parameters to improve anti-tumor immune responses for therapeutic use and to minimize immune effects during diagnostic applications.
"""

METHODS_FEW_SHOT_EXAMPLE = """
### 2. Materials and methods
The complete protocol for this systematic review has been registered in PROSPERO (CRD 42021248743) and published previously [20]. A protocol summary and minor deviations from it are described below.

#### 2.1. Literature search and screening
Our comprehensive search considered four aspects: population, ultrasound, tumor, and immune system. For each of these aspects, search strings were developed and tested that included multiple synonyms for title, abstract, and keyword terms, as well as thesaurus terms (Supplementary Tables S1-S3). We searched Pubmed, Embase via Ovid, and Web of Science Core Collection by RWTH Aachen in September 2021 and updated our search in February 2023. One out of three reviewers (A. R.) removed duplicates using Endnote. Two reviewers (C.P., H.H.) screened the titles and abstracts according to the pre-specified inclusion/exclusion criteria (Supplementary Table S4) using Rayyan [21]. Conflicting results were discussed by all reviewers, and a joint decision was made. Full-text screening followed the same procedure.

#### 2.2. Data extraction
Data on general information (e.g., author, publication year, journal), study characteristics (e.g., species, age, tumor type, ultrasound setting), and reported outcomes (e.g., cytotoxic T cells in tumor or blood) were extracted from all eligible publications by one reviewer (A.R.). Information was extracted from the text, tables, and figures and summarized in tables and graphs.

#### 2.3. Risk-of-bias analysis
The risk-of-bias analysis was performed using the SYRCLE tool [22] for animal studies and the Cochrane RoB2 tool [23] for human studies, as described in [20].

#### 2.4. Meta-analysis
Meta-analyses were performed based on the three most frequently reported outcomes in tumors and blood. When multiple comparisons were extracted from the same publication involving different time points, ultrasound settings, tumor types, etc., they were treated separately and assigned a unique study ID. Values for each comparison were extracted directly from the text or graphs, the latter by using a digital ruler [24]. If one control group was used for multiple comparisons, the number of individuals in the control group was divided by the number of comparisons for which it was used, according to Borenstein et al. [25]. The mean and standard deviation were used to calculate the effect size of each comparison using the statistical software R, version 4.3.1 [26]. Standardized mean effect sizes were compared with the random-effects  model. The between-study heterogeneity was assessed using I2, defined as the percentage of variability in the effect size not caused by sampling error [25]. Small study effects were assessed using a trim-and-fill analysis and visualized in funnel plots [25] using R.

#### 2.5. Subgroup analyses
Subgroup analyses of tumor type, ultrasound settings, mouse strain, sex, and age were performed. Differences between the subgroups were calculated using the Q-test. Strain, sex, and age were only analyzed for studies performed in mice, as the number of studies on other species was too low. Only subgroups with more than five comparisons were considered for each analysis. Thus, only the two most frequently used mouse strains (C57Bl/6 and Balb/c) and four tumor types (melanoma, breast, pancreatic, and colon cancer) were compared. 
Mouse age was categorized into four subgroups: 4–5 weeks, 6–7 weeks, 8–9 weeks, and > 10 weeks. Data from studies were assigned to the appropriate subgroup based on the age to which most mice in the experiment belonged. For example, if a study reported a 6–8 weeks range, the data were assigned to the 6–7 weeks group.
Ultrasound settings were divided into subgroups based on their prevalent biological effects. In this regard, the combination of the applied frequency, pressure, duty cycle, and treatment time determines the energy transmitted into the tissue. Hyperthermia, which is rather induced by protocols with a long duty cycle (often above 50% or using continuous transmission), lower pressure (mostly between 3 and 6 MPa), and longer treatment times (mostly between 5 and 15 min) were distinguished from protocols that rather induce non-thermal effects. These protocols are characterized by a shorter duty cycle (typically 10–20%), higher pressure (in our dataset, a maximum of 12.5 MPa [27]), and shorter treatment times (usually between 2 and 10 min), which resulted in less energy transmission to the tissue. Furthermore, we defined subgroups based on protocols for thermal or mechanical ablation. Subgroups also considered using a sono-sensitzer (SoS, e.g. ROS producing agents), sono-enhancer (SoE, e.g. microbubbles), or additional treatment (e.g., chemotherapeutics), resulting in the following subgroups: mechanical ablation, non-thermal, non-thermal + SoE, nonthermal + SoE + therapy (T), thermal ablation, hyperthermia, hyperthermia + SoS, and hyperthermia + SoS + T. An overview of ultrasound parameters in the subgroups can be found in Fig. 3.

#### 2.6. Protocol deviations
Compared to the published protocol, one member of the review team was replaced (R.G. was replaced by H.H.). Regarding the data  extraction, in addition to the number of immune cells in the blood, concentrations of inflammatory cytokines (e.g., IL-6) in the blood were extracted. In the protocol, we planned to extract the median and range for each comparison for each treatment group, but we extracted the mean and standard deviation to calculate the standardized mean effect sizes. Planned subgroup analyses of the different species were not performed because of an insufficient number of comparisons to generate meaningful results. However, we added subgroup analyses for mouse sex.
"""

RESULTS_FEW_SHOT_EXAMPLE = """
### 3. Results
#### 3.1. Identification of publications and screening
Our searches identified k = 36,318 articles. After removing duplicates, the titles and abstracts of k = 24,401 articles were screened, and k = 531 articles were included in the full-text screening. The inter-rater reliability of κ = 0.67 indicated substantial agreement among the reviewers [28]. During the full-text screening, the reviewers excluded 435 publications, primarily due to a wrong publication type (k = 65), wrong population (k = 29), wrong species (k = 17), wrong intervention (k = 42), wrong study outcome (k = 243), or wrong study design (k = 39) (Fig. 1). In the end, 96 articles were eligible for data extraction.

#### 3.2. Data extraction and Study Characteristics
Available data were extracted from all included papers, including the risk-of-bias data. As with many systematic reviews of animal studies, the overall risk of bias is unclear due to the lack of bias-related information in the manuscripts. Supplementary Fig. S1 provides an overview of publication years, countries, and institutions. Of the 96 articles [27,29–121], k = 6 studies involved humans aged between 40 and 86 years, of both sexes, who had liver, kidney, breast, or prostate tumors [75,98,105,110,112,122], while one study reported results on rats with renal tumors [87]. The remaining k = 89 articles reported results on mice. A majority of these articles used female mice and various mouse strains, with C57Bl/6 and Balb/c being the most common. Moreover, many types of tumors were studied, with breast, melanoma, colon, and pancreatic cancer being the most frequently reported. Additionally, the animals' ages at the beginning of the experiments ranged from 4 to >10 weeks (Fig. 2A). Regarding the ultrasound settings, all subgroups were represented in the available studies. An overview of ultrasound parameters, sonosensitizers, sono-enhancers, and anti-tumor therapies can be found in Fig. 3 and Supplementary Tables S6-S9. Lastly, data on all types of immune cells and many inflammatory markers in tumors and blood were extracted. In the tumor, the three most reported outcomes concerned cytotoxic T cells (CD8+), T helper cells (CD4+), and regulatory T cells (CD4+FoxP3+CD25+), whereas in blood, the inflammatory markers interferon-γ (IFN-γ), interleukin-6 (IL-6), and tumor necrosis factor-α (TNF-α) were most frequently studied (Fig. 2B). A detailed overview of all extracted data is available in Supplementary Tables S5-S9.

#### 3.3. Meta-analysis
Meta-analyses addressed the three outcomes in tumor tissue and blood that were reported in more than k = 5 publications. Tumor-related data showed increased cytotoxic and helper T cell infiltration and reduced regulatory T cell infiltration into tumors upon ultrasound treatment (Fig. 4A, Supplementary Figs. S2-S4). Next to that, the number of macrophages and dendritic cells were increased in tumors after ultrasound exposure (Supplementary Fig. S7). The blood inflammation markers IL-6, and TNF-α were increased after ultrasound treatment (Fig. 3B, Supplementary Figs. S5-S7). IFN-γ was not significantly changed after US treatment, as indicated by the confidence interval which crosses the null effect line. However, it is worth mentioning that funnel plots and trim-and-fill analyses indicated an asymmetric distribution of effect sizes, pointing to small study effects across all conducted meta-analyses, possibly leading to a slight overestimation of the overall standardized effect sizes (Supplementary Fig. S8). Besides, the high between-study heterogeneity (I2) found in all metaanalyses reflects the high variability between study characteristics, which could also influence the effect size. Therefore, we decided to perform subgroup analyses. These were restricted to T cell infiltration into tumors, because the number of included publications was sufficient for meaningful analyses. The number of studies was too low to perform subgroup analyses for blood parameters.

#### 3.4. Subgroup analyses
First, subgroup analyses were performed regarding the mouse strain and sex. There were no differences in immune cell infiltration between the two most used mouse strains (Balb/c and C57Bl/6) nor between the sexes of the mice across all tested cell types (Fig. 5A, B). Specific values are shown in Supplementary Tables S11 and S12. An evidence map (Fig. 5C) illustrates the publication numbers attributed to mouse strain, mouse sex, and tumor type, depicting the high heterogeneity among studies within respective subgroups and explaining the still high between-study heterogeneity (I2). Next, subgroup analyses were performed for mouse age, tumor type, and ultrasound settings. Regarding the mouse age, ultrasound induced significantly stronger effects on cytotoxic and regulatory T cell infiltration in younger mice (4–5 weeks old) compared to older mice. No agerelated differences emerged for T helper cells (Fig. 6A). Furthermore, stronger effects on cytotoxic and regulatory T cells were detected in melanoma and breast compared to other tumors (Fig. 6B). Ultrasound settings were categorized depending on their tendency to produce predominantly non-thermal or thermal effects in tissue. Only a mild influence of non-thermal ultrasound settings on the immune cell infiltration was observed (Fig. 6C). A comparison between the different subgroups using non-thermal ultrasound settings did not show significantdifferences. However, hyperthermia in combination with sonosensitizers (with or without therapy) significantly enhanced the immune response (Fig. 6D). Standardized mean effect sizes of all metaanalyses are available in Supplementary Tables S13 – S16. While it appears that study characteristics like age, tumor type, or ultrasound settings influence immune cell infiltration into tumors, it is important to mention that the high in-between study heterogeneity persists even after subgrouping. Additionally, the evidence distribution map again shows possible confounding by combinations of age, tumor type, and ultrasound settings (Fig. 6E).
"""

DISCUSSION_FEW_SHOT_EXAMPLE = """
4. Discussion
The systematic review provides a comprehensive overview of ultrasound-induced immune effects in tumors. Our extracted data cover results on three species, different tumor types, and multiple ultrasound settings. By integrating these divergent data, we were able to generate robust scientific conclusions. Most groups analyzed whether ultrasound treatment was capable of altering the infiltration of T cells (cytotoxic, helper, and regulatory T cells) into tumors, which are primary targets of immune checkpoint inhibitors [123]. In this regard, high numbers of cytotoxic and low numbers of regulatory T cells (“hot” tumors) predict a favorable immunotherapy response, whereas tumors with high numbers of regulatory and low numbers of cytotoxic T cells (“cold” tumors) might show a low response [55,124]. Van den Ende and colleagues showed in  a systematic review that the tumor immune microenvironment can be modulated into a more immunogenic phenotype by conventional therapies (chemotherapy, radiotherapy and radiochemotherapy) [125]. Our meta-analyses showed increased cytotoxic T cell numbers and decreased regulatory T cell numbers in tumors after ultrasound exposure. Therefore, ultrasound may be capable of converting “cold” tumors, unresponsive to immunotherapy, into responsive “hot” tumors [126] and might be used to prime tumors before applying or in combination with immunotherapies.

Additionally to effects on the primary tumor, higher serum concentrations of the cytokines IL-6 and TNF-α were found. High concentrations of these immunosuppressive cytokines have a detrimental effect on immunotherapies [127,128]. Although these results might be contradictory to the anti-tumor immune response in primary tumors, it has to be mentioned that the number of comparisons in the meta-analyses of blood cytokines were comparably low and the dataset very heterogeneously (e.g., 9 different tumor models, 8 different ultrasound settings). This high heterogeneity between experiments is also represented by the  high I2 values [129]. Therefore, a deeper analysis of the changes in blood cytokines is necessary in future experiments.

The large datasets that we were able to acquire regarding T cell infiltration into primary tumors enabled us to perform subgroup analyses to identify specific study characteristics that might influence the immune response. In this regard, we first analyzed the mouse strain and sex. Elevated pro-inflammatory cytokine and antibody responses in female mice [130] and variations in the immune system between C57Bl/6 and Balb/c mice [131], were previously reported to alter the immune response. However, our analysis did not reveal divergent outcomes between sexes or strains.

Considering the mouse age, we observed an increased anti-tumor immune response in younger mice (e.g., [38,108,132]). This is expected because the immune system is still developing in mice younger than 10 weeks. However, most cancer patients are diagnosed at middle or advanced age, corresponding to mice aged 10 months or older [133]. The importance of age-related changes in immune responses could already be shown in preclinical experiments showing that the immune cell composition in tumors is different and that immune checkpoint inhibitors are less effective in aged mice [134]. Therefore, it is important to avoid an over-interpretation of results from preclinical studies that may not be replicable in clinical scenarios.

Next, we found that an immune response was induced in all analyzed tumor types. A strong reaction was observed in melanoma (e.g., [44,51,117]) a highly immunogenic tumor, for which immunotherapy is an efficient therapeutic strategy [135]. Furthermore, immune responses were observed in breast (e.g., [30,36,90]), pancreatic (e.g., [37,79]), or colon (e.g., [33,46]) cancer, which are less immunogenic tumors. Especially pancreatic [136] and colon [137] cancer are difficult to treat with immunotherapies. Extracellular matrix components of these often desmoplastic tumors suppress anti-tumor responses, and their dense fibrotic network complicates immune cell infiltration [138]. Ultrasound might increase the vascularization and vascular permeability in hypovascular and desmoplastic tumors, facilitating extravasation of immune cells. However, the exact mechanisms need to be further investigated.

Finally, we investigated the effects of different ultrasound parameters. Non-thermal ultrasound moderately altered immune cell  infiltration. Adding sono-enhancers or immunotherapy did not increase the effect. Sono-enhancers for non-thermal ultrasound mostly include microbubbles, nanobubbles, or nanodroplets. Exposing them to ultrasound leads to their oscillation (in the case of microbubbles), resulting in increased vascular permeability and enabling an increased tumor infiltration of immune cells [139] or extravasation of therapeutic agents [40,68,91]. The destruction of sono-enhancers can destroy tumor cells [37,132] and therefore lead to immunogenic cell death, which can trigger an anti-tumor immune response. Although it has been demonstrated that the destruction of tumor vessels can enhance the anti-tumor effects of chemotherapy [140], this approach may not be effective in inducing an anti-tumor immune response, as the infiltration of immune cells into non-vascularized regions might be impaired [33]. Furthermore, these sono-enhancers, especially microbubbles, only oscillate as long as they are exposed to ultrasound, and the duration of their effect on the tissue needs to be thoroughly investigated.

In contrast, thermal ultrasound demonstrated significantly stronger effects on immune cell infiltration when combining hyperthermia with sono-sensitizers (e.g., [36,61,93]). Typically, these sono-sensitizers (e. g., protoporphyrins, chlorophyll derivatives, hematoporphyrin derivatives) generate reactive oxygen species, contributing to immunogenic cell death. Once activated, the sono-sensitizers can act as direct therapeutic agents, inducing enduring tumor effects. The combination of sono-sensitizers with nanoparticles and chemotherapy resulted in an increase in vascular permeability, leading to higher accumulation of chemotherapy and immune cell infiltration [109].

The choice of ultrasound settings depends on the desired effect. Nonthermal settings with sono-enhancers may facilitate immune cell infiltration in desmoplastic tumors like pancreatic cancer by increasing their vascularization and vascular permeability [37]. In our dataset, most pancreatic tumors, which are defined as desmoplastic, were treated with non-thermal ultrasound settings in combination with sono-enhancers, resulting in an anti-tumor immune effect [37,52,79,81]. The treatment of well-vascularized or metastatic tumors may be improved by the application of hyperthermia in combination with sono-sensitizers, which can induce immunogenic cell death, thereby eliciting a systemic immune response in which the primary tumor debris serves as an antigen-presenting site (e.g., [36,99]. Furthermore, sono-sensitizers are often delivered via drug delivery system to overcome their limitations (including low aqueous solubility, toxicity, or low tumor specificity). Consequently, they can therefore be used in combination with other therapeutic agents [141].

Although immunogenic cell death is necessary to induce an immune reaction, complete tumor ablation is not beneficial for inducing an immune response. High temperatures during thermal ablation could lead to protein denaturation, making tumor antigens unrecognizable to antigen-presenting cells [1]. In our dataset, thermal ablation alone did not show a remarkable anti-tumor immune response [48,94].

Of note, the different study characteristics that we analyzed can also influence each other, and this may result in confounding of the data. For example, while ultrasound appears to trigger more pronounced immune effects in younger mice, only mice with melanoma or breast cancer (both resulting in strong immune responses), predominantly treated using thermal ultrasound (also resulting in strong immune responses), were examined at such a young age (e.g., [38,106,108]). Thus, the large effect observed in the young mice may result from a combined effect of age, tumor type, and ultrasound settings.

It is important to note that certain data had to be excluded from subgroup analyses due to a lack of reported information, such as the age or sex of the animals. Another crucial analysis would be the timing of outcome assessment following ultrasound exposure. However, inconsistent reporting between publications made it impossible to generate reliable subgroups. Moreover, there are various ways to report ultrasound settings. For example, publications using non-thermal settings typically report the frequency, pressure, duty cycle, and treatment time. In contrast, those employing thermal settings tend to prefer reporting the acoustic intensity instead of the pressure. A more uniform approach to reporting ultrasound settings would facilitate a more robust comparison of bio effects between different ultrasound protocols.

To conclude, our analyses clearly show that ultrasound treatment induces anti-tumor immune responses. This effect may be promising for priming tumors before or during immunotherapy. However, data generated in young mice can lead to overestimation of the effects for clinical trials, as the immune reaction depends on the age. Finally, the ultrasound parameters and additional application of ultrasound adjuvants should be adapted to the intended effect in the tumor (e.g., increasing vascular permeability, tumor cell destruction). Finally, the results of these meta-analyses can be extrapolated to diagnostic ultrasound, where microbubbles are used as contrast agents. Considering that non-thermal ultrasound using microbubbles increases immune cell infiltration into tumors, the possibility of immunostimulation by diagnostic ultrasound cannot be excluded and should be further investigated.
"""
